import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'fr' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav & General
    'all_tools': 'All Tools',
    'ai_tools': 'Media Tools',
    'compress': 'Compress',
    'convert': 'Convert',
    'edit': 'Edit',
    'dark_mode_light': 'Switch to Light Mode',
    'dark_mode_dark': 'Switch to Dark Mode',
    'toggle_menu': 'Toggle Menu',
    'logo_title': 'MakePDFRight',
    'made_with': 'Made with ❤️ from Kerala',
    'back_home': 'Back to Home',

    // Hero
    'hero_title_1': 'Make Your ',
    'hero_title_2': 'PDFs',
    'hero_title_3': ' Right.',
    'hero_desc': 'Essential tools to organize, convert, and optimize PDFs in your browser.',
    'ai_powered_tools_heading': 'Media & Audio Tools',
    'standard_pdf_tools_heading': 'Standard PDF Tools',

    // Tools Names & Descriptions
    'tools.merge.name': 'Merge PDF',
    'tools.merge.description': 'Combine multiple PDF files into a single document while preserving the original quality.',
    'tools.split.name': 'Split PDF',
    'tools.split.description': 'Split a PDF into individual pages or custom page ranges with ease.',
    'tools.compress.name': 'Compress PDF',
    'tools.compress.description': 'Reduce PDF file size while maintaining the best possible document quality.',
    'tools.pdf_to_word.name': 'PDF to Word',
    'tools.pdf_to_word.description': 'Convert PDF files into fully editable Microsoft Word (.docx) documents with accurate formatting.',
    'tools.pdf_to_excel.name': 'PDF to Excel',
    'tools.pdf_to_excel.description': 'Extract tables and convert PDF data into editable Microsoft Excel (.xlsx) spreadsheets.',
    'tools.pdf_to_jpg.name': 'PDF to JPG',
    'tools.pdf_to_jpg.description': 'Convert every page of your PDF into high-quality JPG images.',
    'tools.image_to_pdf.name': 'Image to PDF',
    'tools.image_to_pdf.description': 'Convert JPG, PNG, WEBP, BMP, and other supported image formats into a professional PDF document.',
    'tools.edit.name': 'Edit PDF',
    'tools.edit.description': 'Edit PDF files by adding text, images, signatures, annotations, shapes, and more.',
    'tools.rotate.name': 'Rotate PDF',
    'tools.rotate.description': 'Rotate one or multiple PDF pages to the correct orientation in seconds.',
    'tools.organise.name': 'Organize PDF',
    'tools.organise.description': 'Reorder, rotate, add, delete, extract, and manage PDF pages with an intuitive interface.',
    'tools.image_gen.name': 'Image Generator',
    'tools.image_gen.description': 'Create custom visuals from text descriptions using advanced models.',
    'tools.generate_image.name': 'AI Image Generator',
    'tools.generate_image.description': 'Create custom visuals from text descriptions using advanced models.',
    'tools.transcribe.name': 'Audio Transcription',
    'tools.transcribe.description': 'Convert voice recordings and audio files into accurate text transcripts.',
    'tools.ocr.name': 'OCR PDF',
    'tools.ocr.description': 'Extract and recognize text from scanned PDF documents with optical character recognition.',

    // ToolPages Title & Details
    'tool.merge.title': 'Merge PDF',
    'tool.merge.desc': 'Combine multiple PDF files into one document in seconds.',
    'tool.split.title': 'Split PDF',
    'tool.split.desc': 'Extract pages from your PDF or split it into multiple files.',
    'tool.compress.title': 'Compress PDF',
    'tool.compress.desc': 'Reduce the size of your PDF while maintaining quality.',
    'tool.pdf_to_jpg.title': 'PDF to JPG',
    'tool.pdf_to_jpg.desc': 'Convert PDF pages into high-quality JPG images.',
    'tool.image_to_pdf.title': 'Image to PDF',
    'tool.image_to_pdf.desc': 'Convert JPG and PNG images to PDF in seconds.',
    'tool.pdf_to_word.title': 'PDF to Word',
    'tool.pdf_to_word.desc': 'Convert your PDF to an editable Word document.',
    'tool.pdf_to_excel.title': 'Convert PDF to Excel',
    'tool.pdf_to_excel.desc': 'Convert PDF data into editable Excel spreadsheets.',
    'tool.edit.title': 'Edit PDF',
    'tool.edit.desc': 'Modify text and add images to your PDF document.',
    'tool.rotate.title': 'Rotate PDF',
    'tool.rotate.desc': 'Rotate your PDF pages and save them permanently.',
    'tool.organise.title': 'Organize PDF',
    'tool.organise.desc': 'Reorder, rotate, add, delete, extract, and manage PDF pages with an intuitive interface.',
    'tool.ocr.title': 'OCR PDF',
    'tool.ocr.desc': 'Perform OCR text recognition on scanned PDF files.',
    'tool.generate_image.title': 'AI Image Generator',
    'tool.generate_image.desc': 'Create custom images and visuals from text prompts.',
    'tool.transcribe.title': 'Audio Transcribe',
    'tool.transcribe.desc': 'Convert audio recordings and voice files into accurate text transcripts.',

    // File Upload
    'upload.choose': 'Choose PDF files',
    'upload.or_drop': 'or drop PDFs here',
    'upload.select_button': 'Select PDF files',
    'upload.drop_active': 'Drop files here...',

    // Core Interaction Buttons / States
    'common.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.success': 'Success!',
    'common.error': 'Error',
    'common.download': 'Download',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.add_files': 'Add more files',
    'common.clear_all': 'Clear all',

    // Specific Tool States
    'merge.merged_title': 'PDFs have been merged!',
    'merge.merged_desc': 'Your combined document is ready for download.',
    'merge.download_btn': 'Download merged PDF',
    'merge.more_btn': 'Merge more files',
    'merge.no_files': 'No files uploaded yet. Add some files to get started.',
    'merge.processing_msg': 'Merging your PDF files in sequence...',

    'split.split_title': 'PDF has been split!',
    'split.split_desc': 'Your extracted pages are ready for download.',
    'split.download_btn': 'Download split pages',
    'split.more_btn': 'Split another file',
    'split.processing_msg': 'Splitting your PDF document...',
    'split.range_label': 'Page Range (e.g. 1-5, 8, 11-13)',
    'split.extract_btn': 'Extract Pages',

    'compress.compressed_title': 'PDF has been compressed!',
    'compress.compressed_desc': 'Your optimized document is ready for download.',
    'compress.download_btn': 'Download compressed PDF',
    'compress.more_btn': 'Compress another file',
    'compress.processing_msg': 'Optimizing and compressing your PDF...',
    'compress.level_label': 'Compression Level',
    'compress.extreme_label': 'Extreme Compression (Lower quality)',
    'compress.recommended_label': 'Recommended Compression (Good quality & size)',
    'compress.less_label': 'Less Compression (High quality)',
    'compress.submit_btn': 'Compress PDF',

    'rotate.rotated_title': 'PDF has been rotated!',
    'rotate.rotated_desc': 'Your modified document is ready for download.',
    'rotate.download_btn': 'Download rotated PDF',
    'rotate.more_btn': 'Rotate another file',
    'rotate.processing_msg': 'Rotating PDF pages...',
    'rotate.clockwise': 'Rotate Clockwise',
    'rotate.counter': 'Rotate Counter-Clockwise',
    'rotate.save_btn': 'Save rotated PDF',

    'organise.saved_title': 'PDF has been organized!',
    'organise.saved_desc': 'Your organized document is ready for download.',
    'organise.download_btn': 'Download organized PDF',
    'organise.more_btn': 'Organize another file',
    'organise.processing_msg': 'Saving page modifications...',
    'organise.drag_reorder': 'Drag to reorder',
    'organise.save_btn': 'Save Changes',

    // Convert Tools
    'convert.success_title': 'Conversion complete!',
    'convert.success_desc': 'Your converted document is ready for download.',
    'convert.download_word': 'Download Word Document',
    'convert.download_excel': 'Download Excel Spreadsheet',
    'convert.download_jpg': 'Download JPG Images',
    'convert.download_pdf': 'Download converted PDF',
    'convert.more_btn': 'Convert another file',
    'convert.processing_word': 'Converting PDF to Word document...',
    'convert.processing_excel': 'Converting PDF to Excel spreadsheet...',
    'convert.processing_jpg': 'Converting PDF to JPG images...',
    'convert.processing_pdf': 'Converting images to PDF...',
    'convert.convert_btn': 'Convert Document',

    // AI Tools
    'ai.image_gen_title': 'Image Generator',
    'ai.image_gen_subtitle': 'Create custom visuals from simple text descriptions.',
    'ai.prompt_placeholder': 'Describe what you want to create (e.g. A futuristic city in cyberpunk style, high detail)...',
    'ai.style_label': 'Visual Style',
    'ai.ratio_label': 'Aspect Ratio',
    'ai.generate_btn': 'Generate Image',
    'ai.generating': 'Generating masterpiece...',
    'ai.download_visual': 'Download Image',
    'ai.image_to_pdf_btn': 'Convert to PDF',

    'ai.transcribe_title': 'Voice & Audio Transcription',
    'ai.transcribe_subtitle': 'Upload audio or record your voice to generate accurate transcription text.',
    'ai.record_start': 'Start Recording',
    'ai.record_stop': 'Stop Recording',
    'ai.upload_audio': 'Upload Audio File',
    'ai.transcribing': 'Transcription in progress...',
    'ai.copy_transcript': 'Copy to Clipboard',
    'ai.download_txt': 'Download Text File',

    // Editor Sidebar panels
    'editor.pages': 'Pages',
    'editor.insert_blank': 'Insert Blank Page',
    'editor.compile_pdf': 'Compile PDF',
    'editor.add_text': 'Add Text',
    'editor.add_image': 'Add Image',
    'editor.freehand': 'Freehand',
    'editor.comments': 'Comments',
    'editor.style': 'Style',
    'editor.insert': 'Insert',
    'editor.ai': 'Assist',
    'editor.track': 'Track Changes',
    'editor.close': 'Close',
    'editor.close_panel': 'Close Panel',
    'editor.saved_title': 'PDF Saved!',
    'editor.saved_desc': 'Your edited document has been successfully compiled.',

    // Auth & Workspace
    'auth.sign_in': 'Sign in',
    'auth.sign_out': 'Sign out',
    'auth.sign_in_google': 'Sign in with Google',
    'auth.account': 'Account',
    'auth.verifying_status': 'Verifying authentication status...',
    'auth.workspace_title': 'AI Document Workspace',
    'auth.workspace_desc': 'Sign in with your Google account to access your personal AI document assistant, query PDF documents, and retain your research workspace.',
    'auth.free_notice_title': '100% Free Core Tools:',
    'auth.free_notice_desc': 'Merge, split, compress, convert, and edit remain completely free and anonymous without any login. Authentication is only required to manage your persistent AI Document Workspace.',
    'auth.dismiss': 'Dismiss',
    'auth.signed_in_securely': 'Signed in securely with Google',
    'auth.connection_verified': 'Secure backend connection verified',
    'auth.connection_failed': 'Unable to verify the secure connection',
    'auth.verify_connection': 'Verify Connection',
    'auth.verifying': 'Verifying...',
    'auth.workspace_badge': 'AI Workspace',
    'auth.workspace_subtitle': 'Interactive document analysis powered by Google Gemini AI',
    'auth.session_info': 'Authenticated Session',
    'auth.connection_status': 'Backend Connection Status',
    'auth.active_notice_title': 'AI Workspace Active',
    'auth.active_notice_desc': 'Your secure session is active and verified.',
    'auth.back_home': 'Back to Home',
    'auth.user_avatar': 'User Avatar',
    'auth.auth_gate_verified': 'Authenticated',
    'auth.no_email': 'No email attached',
    'auth.error_popup_blocked': 'The sign-in popup was blocked by your browser. Please allow popups for this site and try again.',
    'auth.error_cancelled': 'Sign-in was cancelled. Please try again.',
    'auth.error_network': 'Network error connecting to authentication services. Please check your internet connection and try again.',
    'auth.error_unauthorized_domain': 'This application domain is not authorized for authentication. Please check authorized domains configuration.',
    'auth.error_user_disabled': 'This user account has been disabled. Please contact support.',
    'auth.error_generic': 'Unable to complete sign-in. Please try again.',

    // Workspace Management
    'workspace.title': 'Workspaces',
    'workspace.subtitle': 'Manage your private document workspaces and custom system instructions.',
    'workspace.create_new': 'New Workspace',
    'workspace.create_title': 'Create New Workspace',
    'workspace.name_label': 'Workspace Name',
    'workspace.name_placeholder': 'e.g., Legal Contracts Review',
    'workspace.instructions_label': 'Custom System Instructions',
    'workspace.instructions_placeholder': 'e.g., You are a meticulous legal analyst. Focus on liability clauses and indemnification terms...',
    'workspace.instructions_help': 'These instructions guide AI document analysis for this workspace (max 4,000 characters).',
    'workspace.create_btn': 'Create Workspace',
    'workspace.cancel': 'Cancel',
    'workspace.empty_title': 'No Workspaces Yet',
    'workspace.empty_desc': 'Create your first workspace to store custom analysis instructions and manage documents.',
    'workspace.empty_action': 'Create First Workspace',
    'workspace.rename': 'Rename',
    'workspace.rename_title': 'Rename Workspace',
    'workspace.save': 'Save',
    'workspace.save_instructions': 'Save Instructions',
    'workspace.saving': 'Saving...',
    'workspace.saved': 'Instructions saved successfully',
    'workspace.delete': 'Delete',
    'workspace.delete_confirm_title': 'Delete Workspace',
    'workspace.delete_confirm_desc': 'Are you sure you want to delete this workspace? All custom instructions and workspace settings will be permanently removed. This action cannot be undone.',
    'workspace.confirm_delete': 'Yes, Delete Workspace',
    'workspace.error_load': 'Failed to load workspaces.',
    'workspace.error_create': 'Failed to create workspace.',
    'workspace.error_update': 'Failed to update workspace.',
    'workspace.error_delete': 'Failed to delete workspace.',
    'workspace.error_invalid_data': 'Invalid workspace data provided.',
    'workspace.error_not_found': 'Workspace not found.',
    'workspace.error_persistence_unavailable': 'Workspace storage is temporarily unavailable. Please try again later.',
    'workspace.error_unauthorized': 'You must be signed in to manage workspaces.',
    'workspace.error_unknown': 'An unexpected error occurred.',
    'workspace.active': 'Active Workspace',
    'workspace.select': 'Select Workspace',
    'workspace.chars_count': 'characters',
    'workspace.created_at': 'Created',
    'workspace.updated_at': 'Updated',
    'workspace.total_workspaces': 'Total Workspaces',
    'workspace.instructions_empty': 'No custom instructions set yet. Add instructions to customize AI responses for this workspace.',
    'workspace.tab_chat': 'AI Assistant',
    'workspace.tab_instructions': 'Custom Instructions',
    'workspace.chat_placeholder': 'Ask Gemini anything about your PDFs, instructions, or analysis...',
    'workspace.attach_pdf': 'Attach PDF (up to 10MB)',
    'workspace.send_message': 'Send',
    'workspace.sending_message': 'Generating...',
    'workspace.retry_message': 'Retry generation',
    'workspace.empty_chat_title': 'Start your conversation',
    'workspace.empty_chat_desc': 'Ask questions, analyze PDF documents, or test your custom workspace instructions with multi-turn Gemini AI.',
    'workspace.msg_pending': 'Gemini is thinking...',
    'workspace.msg_failed': 'Generation failed. Your prompt is preserved.',
    'workspace.error_rate_limited': 'AI rate limit exceeded. Please wait a moment and try again.',
    'workspace.error_ai_unavailable': 'AI service is temporarily unavailable. Please try again later.',
    'workspace.error_ai_config': 'AI configuration is unavailable on the server.',
    'workspace.error_invalid_pdf': 'Invalid PDF attachment. Must be a valid PDF document under 10MB.',
    'workspace.remove_attachment': 'Remove PDF'
  },
  hi: {
    // Nav & General
    'all_tools': 'सभी टूल्स',
    'ai_tools': 'मीडिया टूल्स',
    'compress': 'कंप्रेस',
    'convert': 'कन्वर्ट',
    'edit': 'एडिट',
    'dark_mode_light': 'लाइट मोड पर स्विच करें',
    'dark_mode_dark': 'डार्क मोड पर स्विच करें',
    'toggle_menu': 'मेन्यू टॉगल करें',
    'logo_title': 'MakePDFRight',
    'made_with': 'केरल से ❤️ के साथ निर्मित',
    'back_home': 'होम पर वापस जाएं',

    // Hero
    'hero_title_1': 'अपने ',
    'hero_title_2': 'PDFs',
    'hero_title_3': ' को सही बनाएं।',
    'hero_desc': 'ब्राउज़र में PDF को व्यवस्थित, रूपांतरित और अनुकूलित करने के लिए आवश्यक उपकरण।',
    'ai_powered_tools_heading': 'मीडिया और ऑडियो टूल्स',
    'standard_pdf_tools_heading': 'मानक PDF टूल्स',

    // Tools Names & Descriptions
    'tools.merge.name': 'PDF मर्ज करें',
    'tools.merge.description': 'सबसे आसान PDF मर्जर के साथ मनचाहे क्रम में PDFs को आपस में जोड़ें।',
    'tools.split.name': 'PDF विभाजित करें',
    'tools.split.description': 'स्वतंत्र PDF फाइलों में आसान रूपांतरण के लिए एक या पूरे पेजों को अलग करें।',
    'tools.compress.name': 'PDF कंप्रेस करें',
    'tools.compress.description': 'अधिकतम PDF गुणवत्ता बनाए रखते हुए फाइल का आकार कम करें।',
    'tools.pdf_to_word.name': 'PDF से वर्ड',
    'tools.pdf_to_word.description': 'अपनी PDF फाइलों को आसानी से संपादन योग्य DOC और DOCX दस्तावेजों में बदलें।',
    'tools.pdf_to_excel.name': 'PDF से एक्सेल',
    'tools.pdf_to_excel.description': 'कुछ ही सेकंड में सीधे PDFs से डेटा निकालकर एक्सेल स्प्रेडशीट में लाएं।',
    'tools.pdf_to_jpg.name': 'PDF से जेपीजी',
    'tools.pdf_to_jpg.description': 'PDF से सभी चित्र निकालें या प्रत्येक पेज को JPG इमेज में बदलें।',
    'tools.image_to_pdf.name': 'इमेज से PDF',
    'tools.image_to_pdf.description': 'JPG, PNG और अन्य छवियों को सेकंडों में PDF में बदलें।',
    'tools.edit.name': 'PDF एडिट करें',
    'tools.edit.description': 'PDF दस्तावेज में टेक्स्ट, इमेज, आकार या फ्रीहैंड एनोटेशन जोड़ें।',
    'tools.rotate.name': 'PDF रोटेट करें',
    'tools.rotate.description': 'अपने PDFs को अपनी आवश्यकता के अनुसार घुमाएं। एक साथ कई PDFs भी घुमा सकते हैं!',
    'tools.organise.name': 'PDF व्यवस्थित करें',
    'tools.organise.description': 'PDF पेजों को क्रमबद्ध करें, जोड़ें और हटाएं। आवश्यकतानुसार घुमाएं और पुनर्व्यवस्थित करें।',
    'tools.image_gen.name': 'इमेज जनरेटर',
    'tools.image_gen.description': 'टेक्स्ट विवरण से कस्टम चित्र बनाएं।',
    'tools.generate_image.name': 'AI इमेज जनरेटर',
    'tools.generate_image.description': 'टेक्स्ट विवरण से कस्टम चित्र बनाएं।',
    'tools.transcribe.name': 'ऑडियो ट्रांसक्रिप्शन',
    'tools.transcribe.description': 'आवाज रिकॉर्डिंग और ऑडियो फाइलों को सटीक पाठ ट्रांसक्रिप्ट में बदलें।',
    'tools.ocr.name': 'OCR PDF',
    'tools.ocr.description': 'स्कैन किए गए PDF दस्तावेजों से टेक्स्ट निकालें।',

    // ToolPages Title & Details
    'tool.merge.title': 'PDF मर्ज करें',
    'tool.merge.desc': 'सैकड़ों PDF फाइलों को सेकंडों में एक दस्तावेज में जोड़ें।',
    'tool.split.title': 'PDF विभाजित करें',
    'tool.split.desc': 'अपने PDF से पेज निकालें या इसे कई फाइलों में विभाजित करें।',
    'tool.compress.title': 'PDF कंप्रेस करें',
    'tool.compress.desc': 'गुणवत्ता बनाए रखते हुए अपने PDF का आकार कम करें।',
    'tool.pdf_to_jpg.title': 'PDF से जेपीजी',
    'tool.pdf_to_jpg.desc': 'PDF पेजों को उच्च-गुणवत्ता वाली JPG छवियों में बदलें।',
    'tool.image_to_pdf.title': 'इमेज से PDF',
    'tool.image_to_pdf.desc': 'JPG और PNG छवियों को सेकंडों में PDF में बदलें।',
    'tool.pdf_to_word.title': 'PDF से वर्ड',
    'tool.pdf_to_word.desc': 'अपने PDF को संपादन योग्य वर्ड दस्तावेज़ में बदलें।',
    'tool.pdf_to_excel.title': 'PDF से एक्सेल',
    'tool.pdf_to_excel.desc': 'PDF से एक्सेल स्प्रेडशीट में टेबल और डेटा निकालें।',
    'tool.edit.title': 'PDF एडिट करें',
    'tool.edit.desc': 'अपने PDF दस्तावेज में टेक्स्ट संशोधित करें और इमेज जोड़ें।',
    'tool.rotate.title': 'PDF रोटेट करें',
    'tool.rotate.desc': 'अपने PDF पेजों को घुमाएं और उन्हें स्थायी रूप से सहेजें।',
    'tool.organise.title': 'PDF व्यवस्थित करें',
    'tool.organise.desc': 'अपने PDF से पेजों को पुनर्व्यवस्थित करें, घुमाएं और हटाएं।',
    'tool.ocr.title': 'OCR PDF',
    'tool.ocr.desc': 'स्कैन किए गए PDF दस्तावेजों से टेक्स्ट पहचानें और निकालें।',
    'tool.generate_image.title': 'AI इमेज जनरेटर',
    'tool.generate_image.desc': 'टेक्स्ट प्रॉम्प्ट से कस्टम चित्र और दृश्य बनाएं।',
    'tool.transcribe.title': 'ऑडियो ट्रांसक्राइब',
    'tool.transcribe.desc': 'ऑडियो रिकॉर्डिंग को सटीक टेक्स्ट में बदलें।',

    // File Upload
    'upload.choose': 'PDF फाइलें चुनें',
    'upload.or_drop': 'या PDF यहाँ ड्रॉप करें',
    'upload.select_button': 'PDF फाइलें चुनें',
    'upload.drop_active': 'फाइलें यहाँ ड्रॉप करें...',

    // Core Interaction Buttons / States
    'common.processing': 'प्रसंस्करण हो रहा है...',
    'common.loading': 'लोड हो रहा है...',
    'common.success': 'सफल!',
    'common.error': 'त्रुटि',
    'common.download': 'डाउनलोड',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.add_files': 'और फाइलें जोड़ें',
    'common.clear_all': 'सभी साफ करें',

    // Specific Tool States
    'merge.merged_title': 'PDFs को मर्ज कर दिया गया है!',
    'merge.merged_desc': 'आपका संयुक्त दस्तावेज़ डाउनलोड के लिए तैयार है।',
    'merge.download_btn': 'मर्ज किया हुआ PDF डाउनलोड करें',
    'merge.more_btn': 'और फाइलें मर्ज करें',
    'merge.no_files': 'अभी तक कोई फाइल अपलोड नहीं की गई है। शुरू करने के लिए कुछ फाइलें जोड़ें।',
    'merge.processing_msg': 'आपके PDF फाइलों को क्रम में मर्ज किया जा रहा है...',

    'split.split_title': 'PDF को विभाजित कर दिया गया है!',
    'split.split_desc': 'आपके निकाले गए पेज डाउनलोड के लिए तैयार हैं।',
    'split.download_btn': 'विभाजित पेज डाउनलोड करें',
    'split.more_btn': 'एक और फ़ाइल विभाजित करें',
    'split.processing_msg': 'आपका PDF दस्तावेज़ विभाजित किया जा रहा है...',
    'split.range_label': 'पेज रेंज (जैसे 1-5, 8, 11-13)',
    'split.extract_btn': 'पेज निकालें',

    'compress.compressed_title': 'PDF कंप्रेस कर दिया गया है!',
    'compress.compressed_desc': 'आपका अनुकूलित दस्तावेज़ डाउनलोड के लिए तैयार है।',
    'compress.download_btn': 'कंप्रेस किया हुआ PDF डाउनलोड करें',
    'compress.more_btn': 'एक और फ़ाइल कंप्रेस करें',
    'compress.processing_msg': 'आपके PDF को अनुकूलित और कंप्रेस किया जा रहा है...',
    'compress.level_label': 'कंप्रेशन का स्तर',
    'compress.extreme_label': 'अत्यधिक कंप्रेशन (कम गुणवत्ता)',
    'compress.recommended_label': 'अनुशंसित कंप्रेशन (अच्छी गुणवत्ता और आकार)',
    'compress.less_label': 'कम कंप्रेशन (उच्च गुणवत्ता)',
    'compress.submit_btn': 'PDF कंप्रेस करें',

    'rotate.rotated_title': 'PDF घुमा दिया गया है!',
    'rotate.rotated_desc': 'आपका संशोधित दस्तावेज़ डाउनलोड के लिए तैयार है।',
    'rotate.download_btn': 'घुमाया हुआ PDF डाउनलोड करें',
    'rotate.more_btn': 'एक और फ़ाइल घुमाएं',
    'rotate.processing_msg': 'PDF पेजों को घुमाया जा रहा है...',
    'rotate.clockwise': 'दक्षिणावर्त घुमाएं (Clockwise)',
    'rotate.counter': 'वामावर्त घुमाएं (Counter-Clockwise)',
    'rotate.save_btn': 'घुमाया हुआ PDF सहेजें',

    'organise.saved_title': 'PDF व्यवस्थित कर दिया गया है!',
    'organise.saved_desc': 'आपका व्यवस्थित दस्तावेज़ डाउनलोड के लिए तैयार है।',
    'organise.download_btn': 'व्यवस्थित PDF डाउनलोड करें',
    'organise.more_btn': 'एक और फ़ाइल व्यवस्थित करें',
    'organise.processing_msg': 'पेज संशोधनों को सहेजा जा रहा है...',
    'organise.drag_reorder': 'पुनः व्यवस्थित करने के लिए खींचें',
    'organise.save_btn': 'परिवर्तन सहेजें',

    // Convert Tools
    'convert.success_title': 'रूपांतरण पूरा हुआ!',
    'convert.success_desc': 'आपका परिवर्तित दस्तावेज़ डाउनलोड के लिए तैयार है।',
    'convert.download_word': 'वर्ड दस्तावेज़ डाउनलोड करें',
    'convert.download_excel': 'एक्सेल स्प्रेडशीट डाउनलोड करें',
    'convert.download_jpg': 'JPG छवियां डाउनलोड करें',
    'convert.download_pdf': 'परिवर्तित PDF डाउनलोड करें',
    'convert.more_btn': 'एक और फ़ाइल बदलें',
    'convert.processing_word': 'PDF को वर्ड दस्तावेज़ में बदला जा रहा है...',
    'convert.processing_excel': 'PDF को एक्सेल स्प्रेडशीट में बदला जा रहा है...',
    'convert.processing_jpg': 'PDF को JPG छवियों में बदला जा रहा है...',
    'convert.processing_pdf': 'छवियों को PDF में बदला जा रहा है...',
    'convert.convert_btn': 'दस्तावेज़ परिवर्तित करें',

    // AI Tools
    'ai.image_gen_title': 'इमेज जनरेटर',
    'ai.image_gen_subtitle': 'सरल पाठ विवरणों से शानदार कस्टम विज़ुअल बनाएं।',
    'ai.prompt_placeholder': 'आप क्या बनाना चाहते हैं उसका विवरण दें (जैसे साइबरपंक शैली में एक भविष्य का शहर, उच्च विवरण)...',
    'ai.style_label': 'दृश्य शैली (Style)',
    'ai.ratio_label': 'पहलू अनुपात (Aspect Ratio)',
    'ai.generate_btn': 'इमेज जनरेट करें',
    'ai.generating': 'मास्टरपीस तैयार की जा रही है...',
    'ai.download_visual': 'इमेज डाउनलोड करें',
    'ai.image_to_pdf_btn': 'PDF में बदलें',

    'ai.transcribe_title': 'वॉयस और ऑडियो ट्रांसक्रिप्शन',
    'ai.transcribe_subtitle': 'अत्यधिक सटीक ट्रांसक्रिप्शन टेक्स्ट जेनरेट करने के लिए ऑडियो अपलोड करें या अपनी आवाज़ रिकॉर्ड करें।',
    'ai.record_start': 'रिकॉर्डिंग शुरू करें',
    'ai.record_stop': 'रिकॉर्डिंग बंद करें',
    'ai.upload_audio': 'ऑडियो फाइल अपलोड करें',
    'ai.transcribing': 'ट्रांसक्रिप्शन प्रगति पर है...',
    'ai.copy_transcript': 'क्लिपबोर्ड पर कॉपी करें',
    'ai.download_txt': 'टेक्स्ट फ़ाइल डाउनलोड करें',

    // Editor Sidebar panels
    'editor.pages': 'पेज',
    'editor.insert_blank': 'खाली पेज डालें',
    'editor.compile_pdf': 'PDF संकलित करें',
    'editor.add_text': 'टेक्स्ट जोड़ें',
    'editor.add_image': 'इमेज जोड़ें',
    'editor.freehand': 'फ्रीहैंड',
    'editor.comments': 'टिप्पणियाँ',
    'editor.style': 'शैली (Style)',
    'editor.insert': 'डालें',
    'editor.ai': 'सहायता',
    'editor.track': 'परिवर्तन ट्रैक करें',
    'editor.close': 'बंद करें',
    'editor.close_panel': 'पैनल बंद करें',
    'editor.saved_title': 'PDF सहेजा गया!',
    'editor.saved_desc': 'आपका संपादित दस्तावेज़ सफलतापूर्वक संकलित हो गया है।',

    // Auth & Workspace
    'auth.sign_in': 'साइन इन करें',
    'auth.sign_out': 'साइन आउट करें',
    'auth.sign_in_google': 'गूगल के साथ साइन इन करें',
    'auth.account': 'खाता',
    'auth.verifying_status': 'प्रमाणीकरण स्थिति की पुष्टि की जा रही है...',
    'auth.workspace_title': 'AI दस्तावेज़ वर्कस्पेस',
    'auth.workspace_desc': 'अपने व्यक्तिगत AI दस्तावेज़ सहायक का उपयोग करने, PDF से प्रश्न पूछने और अपने शोध वर्कस्पेस को बनाए रखने के लिए अपने गूगल खाते से साइन इन करें।',
    'auth.free_notice_title': '100% मुफ्त कोर टूल्स:',
    'auth.free_notice_desc': 'मर्ज, स्प्लिट, कंप्रेस, कन्वर्ट और एडिट बिना किसी लॉगिन के पूरी तरह से मुफ्त और अनाम हैं। प्रमाणीकरण केवल निरंतर AI वर्कस्पेस के लिए आवश्यक है।',
    'auth.dismiss': 'खारिज करें',
    'auth.signed_in_securely': 'गूगल के साथ सुरक्षित रूप से साइन इन किया गया',
    'auth.connection_verified': 'सुरक्षित बैकएंड कनेक्शन सत्यापित',
    'auth.connection_failed': 'सुरक्षित कनेक्शन सत्यापित करने में असमर्थ',
    'auth.verify_connection': 'कनेक्शन सत्यापित करें',
    'auth.verifying': 'सत्यापित किया जा रहा है...',
    'auth.workspace_badge': 'AI वर्कस्पेस',
    'auth.workspace_subtitle': 'Google Gemini AI द्वारा संचालित संवादात्मक दस्तावेज़ विश्लेषण',
    'auth.session_info': 'प्रमाणित सत्र',
    'auth.connection_status': 'बैकएंड कनेक्शन स्थिति',
    'auth.active_notice_title': 'AI वर्कस्पेस सक्रिय',
    'auth.active_notice_desc': 'आपका सुरक्षित सत्र सक्रिय और सत्यापित है।',
    'auth.back_home': 'होम पर वापस जाएं',
    'auth.user_avatar': 'उपयोगकर्ता अवतार',
    'auth.auth_gate_verified': 'प्रमाणित',
    'auth.no_email': 'कोई ईमेल संलग्न नहीं',
    'auth.error_popup_blocked': 'साइन-इन पॉपअप आपके ब्राउज़र द्वारा ब्लॉक कर दिया गया था। कृपया इस साइट के लिए पॉपअप की अनुमति दें और पुन: प्रयास करें।',
    'auth.error_cancelled': 'साइन-इन रद्द कर दिया गया था। कृपया पुन: प्रयास करें।',
    'auth.error_network': 'प्रमाणीकरण सेवाओं से कनेक्ट करने में नेटवर्क त्रुटि। कृपया अपना इंटरनेट कनेक्शन जांचें और पुन: प्रयास करें।',
    'auth.error_unauthorized_domain': 'यह एप्लिकेशन डोमेन प्रमाणीकरण के लिए अधिकृत नहीं है। कृपया अधिकृत डोमेन कॉन्फ़िगरेशन की जांच करें।',
    'auth.error_user_disabled': 'यह उपयोगकर्ता खाता अक्षम कर दिया गया है। कृपया सहायता से संपर्क करें।',
    'auth.error_generic': 'साइन-इन पूरा करने में असमर्थ। कृपया पुन: प्रयास करें।',

    // Workspace Management
    'workspace.title': 'वर्कस्पेस',
    'workspace.subtitle': 'अपने निजी दस्तावेज़ वर्कस्पेस और कस्टम सिस्टम निर्देशों का प्रबंधन करें।',
    'workspace.create_new': 'नया वर्कस्पेस',
    'workspace.create_title': 'नया वर्कस्पेस बनाएं',
    'workspace.name_label': 'वर्कस्पेस का नाम',
    'workspace.name_placeholder': 'उदा. कानूनी अनुबंध समीक्षा',
    'workspace.instructions_label': 'कस्टम सिस्टम निर्देश',
    'workspace.instructions_placeholder': 'उदा. आप एक सतर्क कानूनी विश्लेषक हैं। देयता खंडों पर ध्यान दें...',
    'workspace.instructions_help': 'ये निर्देश इस वर्कस्पेस में दस्तावेज़ विश्लेषण का मार्गदर्शन करते हैं (अधिकतम 4,000 वर्ण)।',
    'workspace.create_btn': 'वर्कस्पेस बनाएं',
    'workspace.cancel': 'रद्द करें',
    'workspace.empty_title': 'अभी तक कोई वर्कस्पेस नहीं',
    'workspace.empty_desc': 'कस्टम निर्देश सहेजने और दस्तावेज़ प्रबंधित करने के लिए अपना पहला वर्कस्पेस बनाएं।',
    'workspace.empty_action': 'पहला वर्कस्पेस बनाएं',
    'workspace.rename': 'नाम बदलें',
    'workspace.rename_title': 'वर्कस्पेस का नाम बदलें',
    'workspace.save': 'सहेजें',
    'workspace.save_instructions': 'निर्देश सहेजें',
    'workspace.saving': 'सहेजा जा रहा है...',
    'workspace.saved': 'निर्देश सफलतापूर्वक सहेजे गए',
    'workspace.delete': 'हटाएं',
    'workspace.delete_confirm_title': 'वर्कस्पेस हटाएं',
    'workspace.delete_confirm_desc': 'क्या आप वाकई इस वर्कस्पेस को हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    'workspace.confirm_delete': 'हाँ, वर्कस्पेस हटाएं',
    'workspace.error_load': 'वर्कस्पेस लोड करने में विफल।',
    'workspace.error_create': 'वर्कस्पेस बनाने में विफल।',
    'workspace.error_update': 'वर्कस्पेस अपडेट करने में विफल।',
    'workspace.error_delete': 'वर्कस्पेस हटाने में विफल।',
    'workspace.error_invalid_data': 'अमान्य वर्कस्पेस डेटा प्रदान किया गया।',
    'workspace.error_not_found': 'वर्कस्पेस नहीं मिला।',
    'workspace.error_persistence_unavailable': 'वर्कस्पेस स्टोरेज अस्थायी रूप से अनुपलब्ध है। कृपया बाद में पुन: प्रयास करें।',
    'workspace.error_unauthorized': 'वर्कस्पेस प्रबंधित करने के लिए आपको साइन इन होना आवश्यक है।',
    'workspace.error_unknown': 'एक अप्रत्याशित त्रुटि हुई।',
    'workspace.active': 'सक्रिय वर्कस्पेस',
    'workspace.select': 'वर्कस्पेस चुनें',
    'workspace.chars_count': 'वर्ण',
    'workspace.created_at': 'निर्मित',
    'workspace.updated_at': 'अपडेट किया गया',
    'workspace.total_workspaces': 'कुल वर्कस्पेस',
    'workspace.instructions_empty': 'अभी तक कोई कस्टम निर्देश सेट नहीं किए गए हैं।'
  },
  fr: {
    // Nav & General
    'all_tools': 'Tous les outils',
    'ai_tools': 'Outils Média',
    'compress': 'Compresser',
    'convert': 'Convertir',
    'edit': 'Modifier',
    'dark_mode_light': 'Passer au mode clair',
    'dark_mode_dark': 'Passer au mode sombre',
    'toggle_menu': 'Basculer le menu',
    'logo_title': 'MakePDFRight',
    'made_with': 'Fait avec ❤️ du Kerala',
    'back_home': 'Retour à l\'accueil',

    // Hero
    'hero_title_1': 'Rendez vos ',
    'hero_title_2': 'PDF',
    'hero_title_3': ' Parfaits.',
    'hero_desc': 'Outils essentiels pour organiser, convertir et optimiser vos PDF directement dans votre navigateur.',
    'ai_powered_tools_heading': 'Outils Média & Audio',
    'standard_pdf_tools_heading': 'Outils PDF Standards',

    // Tools Names & Descriptions
    'tools.merge.name': 'Fusionner PDF',
    'tools.merge.description': 'Combinez vos PDF dans l\'ordre de votre choix avec le fusionneur le plus simple disponible.',
    'tools.split.name': 'Diviser PDF',
    'tools.split.description': 'Séparez une page ou tout un ensemble pour une conversion facile en fichiers PDF indépendants.',
    'tools.compress.name': 'Compresser PDF',
    'tools.compress.description': 'Réduisez la taille du fichier tout en optimisant pour une qualité PDF maximale.',
    'tools.pdf_to_word.name': 'PDF en Word',
    'tools.pdf_to_word.description': 'Convertissez facilement vos fichiers PDF en documents DOC et DOCX modifiables.',
    'tools.pdf_to_excel.name': 'PDF en Excel',
    'tools.pdf_to_excel.description': 'Extrayez des données directement des PDF vers des feuilles Excel en quelques secondes.',
    'tools.pdf_to_jpg.name': 'PDF en JPG',
    'tools.pdf_to_jpg.description': 'Extrayez toutes les images d\'un PDF ou convertissez chaque page en image JPG.',
    'tools.image_to_pdf.name': 'Image en PDF',
    'tools.image_to_pdf.description': 'Convertissez des images JPG, PNG et autres en PDF en quelques secondes.',
    'tools.edit.name': 'Modifier PDF',
    'tools.edit.description': 'Ajoutez du texte, des images, des formes ou des annotations libres à un document PDF.',
    'tools.rotate.name': 'Faire pivoter PDF',
    'tools.rotate.description': 'Faites pivoter vos PDF comme vous le souhaitez. Vous pouvez même en faire pivoter plusieurs à la fois !',
    'tools.organise.name': 'Organiser PDF',
    'tools.organise.description': 'Triez, ajoutez et supprimez des pages PDF. Pivotez et réorganisez-les selon vos besoins.',
    'tools.image_gen.name': 'Générateur d\'images',
    'tools.image_gen.description': 'Créez de superbes visuels à partir de descriptions textuelles à l\'aide de modèles avancés.',
    'tools.generate_image.name': 'Générateur d\'images IA',
    'tools.generate_image.description': 'Créez de superbes visuels à partir de descriptions textuelles.',
    'tools.transcribe.name': 'Transcription Audio',
    'tools.transcribe.description': 'Convertissez des enregistrements vocaux et des fichiers audio en transcriptions textuelles précises.',
    'tools.ocr.name': 'OCR PDF',
    'tools.ocr.description': 'Extrayez le texte des documents PDF numérisés avec l\'OCR.',

    // ToolPages Title & Details
    'tool.merge.title': 'Fusionner PDF',
    'tool.merge.desc': 'Combinez plusieurs fichiers PDF en un seul document en quelques secondes.',
    'tool.split.title': 'Diviser PDF',
    'tool.split.desc': 'Extrayez des pages de votre PDF ou divisez-le en plusieurs fichiers.',
    'tool.compress.title': 'Compresser PDF',
    'tool.compress.desc': 'Réduisez la taille de votre PDF tout en conservant sa qualité.',
    'tool.pdf_to_jpg.title': 'PDF en JPG',
    'tool.pdf_to_jpg.desc': 'Convertissez des pages PDF en images JPG de haute qualité.',
    'tool.image_to_pdf.title': 'Image en PDF',
    'tool.image_to_pdf.desc': 'Convertissez des images JPG et PNG en PDF en quelques secondes.',
    'tool.pdf_to_word.title': 'PDF en Word',
    'tool.pdf_to_word.desc': 'Convertissez votre PDF en un document Word modifiable.',
    'tool.pdf_to_excel.title': 'PDF en Excel',
    'tool.pdf_to_excel.desc': 'Extrayez des tableaux et des données de PDF vers des feuilles Excel.',
    'tool.edit.title': 'Modifier PDF',
    'tool.edit.desc': 'Modifiez le texte et ajoutez des images à votre document PDF.',
    'tool.rotate.title': 'Faire pivoter PDF',
    'tool.rotate.desc': 'Faites pivoter les pages de votre PDF et enregistrez-les de manière permanente.',
    'tool.organise.title': 'Organiser PDF',
    'tool.organise.desc': 'Réorganisez, faites pivoter et supprimez des pages de votre PDF.',
    'tool.ocr.title': 'OCR PDF',
    'tool.ocr.desc': 'Extrayez le texte des fichiers PDF numérisés.',
    'tool.generate_image.title': 'Générateur d\'images IA',
    'tool.generate_image.desc': 'Créez des images personnalisées à partir d\'invites textuelles.',
    'tool.transcribe.title': 'Transcription Audio',
    'tool.transcribe.desc': 'Convertissez les enregistrements vocaux en transcriptions textuelles précises.',

    // File Upload
    'upload.choose': 'Choisir des fichiers PDF',
    'upload.or_drop': 'ou déposer les PDF ici',
    'upload.select_button': 'Sélectionner des fichiers PDF',
    'upload.drop_active': 'Déposez les fichiers ici...',

    // Core Interaction Buttons / States
    'common.processing': 'Traitement en cours...',
    'common.loading': 'Chargement...',
    'common.success': 'Succès !',
    'common.error': 'Erreur',
    'common.download': 'Télécharger',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.add_files': 'Ajouter des fichiers',
    'common.clear_all': 'Tout effacer',

    // Specific Tool States
    'merge.merged_title': 'Les PDF ont été fusionnés !',
    'merge.merged_desc': 'Votre document combiné est prêt pour le téléchargement.',
    'merge.download_btn': 'Télécharger le PDF fusionné',
    'merge.more_btn': 'Fusionner plus de fichiers',
    'merge.no_files': 'Aucun fichier téléchargé. Ajoutez des fichiers pour commencer.',
    'merge.processing_msg': 'Fusion de vos fichiers PDF en séquence...',

    'split.split_title': 'Le PDF a été divisé !',
    'split.split_desc': 'Vos pages extraites sont prêtes pour le téléchargement.',
    'split.download_btn': 'Télécharger les pages divisées',
    'split.more_btn': 'Diviser un autre fichier',
    'split.processing_msg': 'Division de votre document PDF en cours...',
    'split.range_label': 'Plage de pages (ex: 1-5, 8, 11-13)',
    'split.extract_btn': 'Extraire les pages',

    'compress.compressed_title': 'Le PDF a été compressé !',
    'compress.compressed_desc': 'Votre document optimisé est prêt pour le téléchargement.',
    'compress.download_btn': 'Télécharger le PDF compressé',
    'compress.more_btn': 'Compresser un autre fichier',
    'compress.processing_msg': 'Optimisation et compression de votre PDF...',
    'compress.level_label': 'Niveau de compression',
    'compress.extreme_label': 'Compression extrême (Qualité inférieure)',
    'compress.recommended_label': 'Compression recommandée (Bonne qualité & taille)',
    'compress.less_label': 'Moins de compression (Haute qualité)',
    'compress.submit_btn': 'Compresser le PDF',

    'rotate.rotated_title': 'Le PDF a été pivoté !',
    'rotate.rotated_desc': 'Votre document modifié est prêt pour le téléchargement.',
    'rotate.download_btn': 'Télécharger le PDF pivoté',
    'rotate.more_btn': 'Faire pivoter un autre fichier',
    'rotate.processing_msg': 'Rotation des pages du PDF...',
    'rotate.clockwise': 'Rotation horaire',
    'rotate.counter': 'Rotation antihoraire',
    'rotate.save_btn': 'Enregistrer le PDF pivoté',

    'organise.saved_title': 'Le PDF a été organisé !',
    'organise.saved_desc': 'Votre document organisé est prêt pour le téléchargement.',
    'organise.download_btn': 'Télécharger le PDF organisé',
    'organise.more_btn': 'Organiser un autre fichier',
    'organise.processing_msg': 'Enregistrement des modifications...',
    'organise.drag_reorder': 'Faire glisser pour réordonner',
    'organise.save_btn': 'Enregistrer les modifications',

    // Convert Tools
    'convert.success_title': 'Conversion réussie !',
    'convert.success_desc': 'Votre document converti est prêt pour le téléchargement.',
    'convert.download_word': 'Télécharger le document Word',
    'convert.download_excel': 'Télécharger la feuille Excel',
    'convert.download_jpg': 'Télécharger les images JPG',
    'convert.download_pdf': 'Télécharger le PDF converti',
    'convert.more_btn': 'Convertir un autre fichier',
    'convert.processing_word': 'Conversion du PDF en document Word...',
    'convert.processing_excel': 'Conversion du PDF en feuille Excel...',
    'convert.processing_jpg': 'Conversion du PDF en images JPG...',
    'convert.processing_pdf': 'Conversion des images en PDF...',
    'convert.convert_btn': 'Convertir le document',

    // AI Tools
    'ai.image_gen_title': 'Générateur d\'images',
    'ai.image_gen_subtitle': 'Créez de superbes visuels personnalisés à partir de simples descriptions textuelles.',
    'ai.prompt_placeholder': 'Décrivez ce que vous souhaitez créer (ex: Une ville futuriste de style cyberpunk, haute définition)...',
    'ai.style_label': 'Style visuel',
    'ai.ratio_label': 'Format d\'image',
    'ai.generate_btn': 'Générer l\'image',
    'ai.generating': 'Génération du chef-d\'œuvre...',
    'ai.download_visual': 'Télécharger l\'image',
    'ai.image_to_pdf_btn': 'Convertir en PDF',

    'ai.transcribe_title': 'Transcription Vocale & Audio',
    'ai.transcribe_subtitle': 'Téléchargez un fichier audio ou enregistrez votre voix pour générer une transcription ultra-précise.',
    'ai.record_start': 'Démarrer l\'enregistrement',
    'ai.record_stop': 'Arrêter l\'enregistrement',
    'ai.upload_audio': 'Télécharger un fichier audio',
    'ai.transcribing': 'Transcription en cours...',
    'ai.copy_transcript': 'Copier dans le presse-papiers',
    'ai.download_txt': 'Télécharger le fichier texte',

    // Editor Sidebar panels
    'editor.pages': 'Pages',
    'editor.insert_blank': 'Insérer une page blanche',
    'editor.compile_pdf': 'Compiler le PDF',
    'editor.add_text': 'Ajouter du texte',
    'editor.add_image': 'Ajouter une image',
    'editor.freehand': 'Dessin libre',
    'editor.comments': 'Commentaires',
    'editor.style': 'Style',
    'editor.insert': 'Insérer',
    'editor.ai': 'Assistance',
    'editor.track': 'Suivi des modifs',
    'editor.close': 'Fermer',
    'editor.close_panel': 'Fermer le panneau',
    'editor.saved_title': 'PDF enregistré !',
    'editor.saved_desc': 'Votre document modifié a été compilé avec succès.',

    // Auth & Workspace
    'auth.sign_in': 'Se connecter',
    'auth.sign_out': 'Se déconnecter',
    'auth.sign_in_google': 'Se connecter avec Google',
    'auth.account': 'Compte',
    'auth.verifying_status': 'Vérification de l\'authentification...',
    'auth.workspace_title': 'Espace de travail IA',
    'auth.workspace_desc': 'Connectez-vous avec Google pour accéder à votre assistant documentaire IA personnel, analyser vos PDF et conserver votre espace de recherche.',
    'auth.free_notice_title': 'Outils principaux 100% gratuits :',
    'auth.free_notice_desc': 'Fusionner, diviser, compresser, convertir et modifier restent totalement gratuits et anonymes sans connexion. L\'authentification est requise uniquement pour l\'espace IA persistant.',
    'auth.dismiss': 'Fermer',
    'auth.signed_in_securely': 'Connecté en toute sécurité avec Google',
    'auth.connection_verified': 'Connexion backend sécurisée vérifiée',
    'auth.connection_failed': 'Impossible de vérifier la connexion sécurisée',
    'auth.verify_connection': 'Vérifier la connexion',
    'auth.verifying': 'Vérification...',
    'auth.workspace_badge': 'Espace IA',
    'auth.workspace_subtitle': 'Analyse documentaire interactive alimentée par Google Gemini AI',
    'auth.session_info': 'Session authentifiée',
    'auth.connection_status': 'Statut de la connexion backend',
    'auth.active_notice_title': 'Espace IA actif',
    'auth.active_notice_desc': 'Votre session sécurisée est active et vérifiée.',
    'auth.back_home': 'Retour à l\'accueil',
    'auth.user_avatar': 'Avatar utilisateur',
    'auth.auth_gate_verified': 'Authentifié',
    'auth.no_email': 'Aucun e-mail associé',
    'auth.error_popup_blocked': 'La fenêtre contextuelle de connexion a été bloquée par votre navigateur. Veuillez autoriser les fenêtres contextuelles pour ce site et réessayer.',
    'auth.error_cancelled': 'La connexion a été annulée. Veuillez réessayer.',
    'auth.error_network': 'Erreur réseau lors de la connexion aux services d\'authentification. Veuillez vérifier votre connexion Internet et réessayer.',
    'auth.error_unauthorized_domain': 'Ce domaine d\'application n\'est pas autorisé pour l\'authentification. Veuillez vérifier la configuration des domaines autorisés.',
    'auth.error_user_disabled': 'Ce compte utilisateur a été désactivé. Veuillez contacter le support.',
    'auth.error_generic': 'Impossible de terminer la connexion. Veuillez réessayer.',

    // Workspace Management
    'workspace.title': 'Espaces de travail',
    'workspace.subtitle': 'Gérez vos espaces documentaires privés et vos instructions système personnalisées.',
    'workspace.create_new': 'Nouvel espace',
    'workspace.create_title': 'Créer un nouvel espace',
    'workspace.name_label': 'Nom de l\'espace',
    'workspace.name_placeholder': 'ex. Revue de contrats juridiques',
    'workspace.instructions_label': 'Instructions système personnalisées',
    'workspace.instructions_placeholder': 'ex. Vous êtes un juriste méticuleux. Concentrez-vous sur les clauses de responsabilité...',
    'workspace.instructions_help': 'Ces instructions orientent l\'analyse IA des documents pour cet espace (max 4 000 caractères).',
    'workspace.create_btn': 'Créer l\'espace',
    'workspace.cancel': 'Annuler',
    'workspace.empty_title': 'Aucun espace pour l\'instant',
    'workspace.empty_desc': 'Créez votre premier espace pour enregistrer des instructions personnalisées et gérer vos documents.',
    'workspace.empty_action': 'Créer un premier espace',
    'workspace.rename': 'Renommer',
    'workspace.rename_title': 'Renommer l\'espace',
    'workspace.save': 'Enregistrer',
    'workspace.save_instructions': 'Enregistrer les instructions',
    'workspace.saving': 'Enregistrement...',
    'workspace.saved': 'Instructions enregistrées avec succès',
    'workspace.delete': 'Supprimer',
    'workspace.delete_confirm_title': 'Supprimer l\'espace',
    'workspace.delete_confirm_desc': 'Êtes-vous sûr de vouloir supprimer cet espace ? Cette action est irréversible.',
    'workspace.confirm_delete': 'Oui, supprimer l\'espace',
    'workspace.error_load': 'Échec du chargement des espaces.',
    'workspace.error_create': 'Échec de la création de l\'espace.',
    'workspace.error_update': 'Échec de la mise à jour de l\'espace.',
    'workspace.error_delete': 'Échec de la suppression de l\'espace.',
    'workspace.error_invalid_data': 'Données d\'espace de travail invalides fournies.',
    'workspace.error_not_found': 'Espace de travail introuvable.',
    'workspace.error_persistence_unavailable': 'Le stockage de l\'espace de travail est temporairement indisponible. Veuillez réessayer plus tard.',
    'workspace.error_unauthorized': 'Vous devez être connecté pour gérer les espaces de travail.',
    'workspace.error_unknown': 'Une erreur inattendue est survenue.',
    'workspace.active': 'Espace actif',
    'workspace.select': 'Sélectionner l\'espace',
    'workspace.chars_count': 'caractères',
    'workspace.created_at': 'Créé le',
    'workspace.updated_at': 'Mis à jour le',
    'workspace.total_workspaces': 'Total des espaces',
    'workspace.instructions_empty': 'Aucune instruction personnalisée pour le moment.'
  },
  de: {
    // Nav & General
    'all_tools': 'Alle Tools',
    'ai_tools': 'Medien-Tools',
    'compress': 'Komprimieren',
    'convert': 'Konvertieren',
    'edit': 'Bearbeiten',
    'dark_mode_light': 'In den hellen Modus wechseln',
    'dark_mode_dark': 'In den dunklen Modus wechseln',
    'toggle_menu': 'Menü umschalten',
    'logo_title': 'MakePDFRight',
    'made_with': 'Hergestellt mit ❤️ aus Kerala',
    'back_home': 'Zurück zur Startseite',

    // Hero
    'hero_title_1': 'Machen Sie Ihre ',
    'hero_title_2': 'PDFs',
    'hero_title_3': ' Richtig.',
    'hero_desc': 'Wichtige Tools zum Organisieren, Konvertieren und Optimieren von PDFs direkt in Ihrem Browser.',
    'ai_powered_tools_heading': 'Medien- & Audio-Tools',
    'standard_pdf_tools_heading': 'Standard PDF-Tools',

    // Tools Names & Descriptions
    'tools.merge.name': 'PDF zusammenführen',
    'tools.merge.description': 'Kombinieren Sie PDFs in der gewünschten Reihenfolge mit dem einfachsten verfügbaren PDF-Merger.',
    'tools.split.name': 'PDF teilen',
    'tools.split.description': 'Trennen Sie eine einzelne Seite oder einen ganzen Satz für eine einfache Konvertierung in unabhängige PDF-Dateien.',
    'tools.compress.name': 'PDF komprimieren',
    'tools.compress.description': 'Reduzieren Sie die Dateigröße bei gleichzeitiger Optimierung für maximale PDF-Qualität.',
    'tools.pdf_to_word.name': 'PDF in Word',
    'tools.pdf_to_word.description': 'Konvertieren Sie Ihre PDF-Dateien ganz einfach in leicht bearbeitbare DOC- und DOCX-Dokumente.',
    'tools.pdf_to_excel.name': 'PDF in Excel',
    'tools.pdf_to_excel.description': 'Laden Sie Daten in wenigen Sekunden direkt aus PDFs in Excel-Tabellen.',
    'tools.pdf_to_jpg.name': 'PDF in JPG',
    'tools.pdf_to_jpg.description': 'Extrahieren Sie alle Bilder aus einer PDF-Datei oder konvertieren Sie jede Seite in ein JPG-Bild.',
    'tools.image_to_pdf.name': 'Bild in PDF',
    'tools.image_to_pdf.description': 'Konvertieren Sie JPG, PNG und andere Bilder in Sekundenschnelle in PDF.',
    'tools.edit.name': 'PDF bearbeiten',
    'tools.edit.description': 'Fügen Sie Text, Bilder, Formen oder Freihand-Anmerkungen zu einem PDF-Dokument hinzu.',
    'tools.rotate.name': 'PDF drehen',
    'tools.rotate.description': 'Drehen Sie Ihre PDFs so, wie Sie sie benötigen. Sie können sogar mehrere PDFs auf einmal drehen!',
    'tools.organise.name': 'PDF organisieren',
    'tools.organise.description': 'Seiten sortieren, hinzufügen und löschen. Drehen und ordnen Sie sie nach Ihren Bedürfnissen neu an.',
    'tools.image_gen.name': 'Bildgenerator',
    'tools.image_gen.description': 'Erstellen Sie atemberaubende Bilder aus Textbeschreibungen mit fortschrittlichen Modellen.',
    'tools.generate_image.name': 'KI-Bildgenerator',
    'tools.generate_image.description': 'Erstellen Sie atemberaubende Bilder aus Textbeschreibungen.',
    'tools.transcribe.name': 'Audio-Transkription',
    'tools.transcribe.description': 'Konvertieren Sie Sprachaufnahmen und Audiodateien in präzise Texttranskripte.',
    'tools.ocr.name': 'OCR PDF',
    'tools.ocr.description': 'Extrahieren Sie Text aus gescannten PDF-Dokumenten.',

    // ToolPages Title & Details
    'tool.merge.title': 'PDF zusammenführen',
    'tool.merge.desc': 'Kombinieren Sie mehrere PDF-Dateien in Sekundenschnelle zu einem Dokument.',
    'tool.split.title': 'PDF teilen',
    'tool.split.desc': 'Extrahieren Sie Seiten aus Ihrem PDF oder teilen Sie es in mehrere Dateien auf.',
    'tool.compress.title': 'PDF komprimieren',
    'tool.compress.desc': 'Reduzieren Sie die Größe Ihres PDFs bei gleichbleibender Qualität.',
    'tool.pdf_to_jpg.title': 'PDF in JPG',
    'tool.pdf_to_jpg.desc': 'Konvertieren Sie PDF-Seiten in hochwertige JPG-Bilder.',
    'tool.image_to_pdf.title': 'Bild in PDF',
    'tool.image_to_pdf.desc': 'Konvertieren Sie JPG- und PNG-Bilder in Sekundenschnelle in PDF.',
    'tool.pdf_to_word.title': 'PDF in Word',
    'tool.pdf_to_word.desc': 'Konvertieren Sie Ihr PDF in ein bearbeitbares Word-Dokument.',
    'tool.pdf_to_excel.title': 'PDF in Excel',
    'tool.pdf_to_excel.desc': 'Extrahieren Sie Tabellen und Daten aus PDFs in Excel-Tabellen.',
    'tool.edit.title': 'PDF bearbeiten',
    'tool.edit.desc': 'Ändern Sie Text und fügen Sie Bilder zu Ihrem PDF-Dokument hinzu.',
    'tool.rotate.title': 'PDF drehen',
    'tool.rotate.desc': 'Drehen Sie Ihre PDF-Seiten und speichern Sie sie dauerhaft.',
    'tool.organise.title': 'PDF organisieren',
    'tool.organise.desc': 'Ordnen, drehen und löschen Sie Seiten aus Ihrem PDF.',
    'tool.ocr.title': 'OCR PDF',
    'tool.ocr.desc': 'Führen Sie eine optische Zeichenerkennung bei gescannten PDFs durch.',
    'tool.generate_image.title': 'KI-Bildgenerator',
    'tool.generate_image.desc': 'Erstellen Sie benutzerdefinierte Bilder aus Textanweisungen.',
    'tool.transcribe.title': 'Audio-Transkription',
    'tool.transcribe.desc': 'Konvertieren Sie Audioaufnahmen in präzisen Text.',

    // File Upload
    'upload.choose': 'PDF-Dateien auswählen',
    'upload.or_drop': 'oder PDFs hier ablegen',
    'upload.select_button': 'PDF-Dateien auswählen',
    'upload.drop_active': 'Dateien hier ablegen...',

    // Core Interaction Buttons / States
    'common.processing': 'Verarbeitung...',
    'common.loading': 'Laden...',
    'common.success': 'Erfolg!',
    'common.error': 'Fehler',
    'common.download': 'Herunterladen',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.add_files': 'Dateien hinzufügen',
    'common.clear_all': 'Alles löschen',

    // Specific Tool States
    'merge.merged_title': 'PDFs wurden zusammengeführt!',
    'merge.merged_desc': 'Ihr kombiniertes Dokument steht zum Download bereit.',
    'merge.download_btn': 'Zusammengeführte PDF herunterladen',
    'merge.more_btn': 'Weitere Dateien zusammenführen',
    'merge.no_files': 'Noch keine Dateien hochgeladen. Fügen Sie Dateien hinzu, um zu beginnen.',
    'merge.processing_msg': 'Führe deine PDF-Dateien der Reihe nach zusammen...',

    'split.split_title': 'PDF wurde geteilt!',
    'split.split_desc': 'Ihre extrahierten Seiten stehen zum Download bereit.',
    'split.download_btn': 'Geteilte Seiten herunterladen',
    'split.more_btn': 'Weitere Datei teilen',
    'split.processing_msg': 'Teile Ihr PDF-Dokument...',
    'split.range_label': 'Seitenbereich (z.B. 1-5, 8, 11-13)',
    'split.extract_btn': 'Seiten extrahieren',

    'compress.compressed_title': 'PDF wurde komprimiert!',
    'compress.compressed_desc': 'Ihr optimiertes Dokument steht zum Download bereit.',
    'compress.download_btn': 'Komprimierte PDF herunterladen',
    'compress.more_btn': 'Weitere Datei komprimieren',
    'compress.processing_msg': 'Optimieren und Komprimieren Ihres PDFs...',
    'compress.level_label': 'Komprimierungsstufe',
    'compress.extreme_label': 'Extreme Komprimierung (Geringere Qualität)',
    'compress.recommended_label': 'Empfohlene Komprimierung (Gute Qualität & Größe)',
    'compress.less_label': 'Weniger Komprimierung (Hohe Qualität)',
    'compress.submit_btn': 'PDF komprimieren',

    'rotate.rotated_title': 'PDF wurde gedreht!',
    'rotate.rotated_desc': 'Ihr geändertes Dokument steht zum Download bereit.',
    'rotate.download_btn': 'Gedrehtes PDF herunterladen',
    'rotate.more_btn': 'Weitere Datei drehen',
    'rotate.processing_msg': 'PDF-Seiten werden gedreht...',
    'rotate.clockwise': 'Im Uhrzeigersinn drehen',
    'rotate.counter': 'Gegen den Uhrzeigersinn drehen',
    'rotate.save_btn': 'Gedrehtes PDF speichern',

    'organise.saved_title': 'PDF wurde organisiert!',
    'organise.saved_desc': 'Ihr organisiertes Dokument steht zum Download bereit.',
    'organise.download_btn': 'Organisiertes PDF herunterladen',
    'organise.more_btn': 'Weitere Datei organisieren',
    'organise.processing_msg': 'Änderungen werden gespeichert...',
    'organise.drag_reorder': 'Zum Neuanordnen ziehen',
    'organise.save_btn': 'Änderungen speichern',

    // Convert Tools
    'convert.success_title': 'Konvertierung abgeschlossen!',
    'convert.success_desc': 'Ihr konvertiertes Dokument steht zum Download bereit.',
    'convert.download_word': 'Word-Dokument herunterladen',
    'convert.download_excel': 'Excel-Tabelle herunterladen',
    'convert.download_jpg': 'JPG-Bilder herunterladen',
    'convert.download_pdf': 'Konvertiertes PDF herunterladen',
    'convert.more_btn': 'Weitere Datei konvertieren',
    'convert.processing_word': 'Konvertiere PDF in Word-Dokument...',
    'convert.processing_excel': 'Konvertiere PDF in Excel-Tabelle...',
    'convert.processing_jpg': 'Konvertiere PDF in JPG-Bilder...',
    'convert.processing_pdf': 'Konvertiere Bilder in PDF...',
    'convert.convert_btn': 'Dokument konvertieren',

    // AI Tools
    'ai.image_gen_title': 'Bildgenerator',
    'ai.image_gen_subtitle': 'Erstellen Sie atemberaubende benutzerdefinierte Grafiken aus einfachen Textbeschreibungen.',
    'ai.prompt_placeholder': 'Beschreiben Sie, was Sie erstellen möchten (z. B. Eine futuristische Stadt im Cyberpunk-Stil, hohe Details)...',
    'ai.style_label': 'Visueller Stil',
    'ai.ratio_label': 'Seitenverhältnis',
    'ai.generate_btn': 'Bild generieren',
    'ai.generating': 'Meisterwerk wird generiert...',
    'ai.download_visual': 'Bild herunterladen',
    'ai.image_to_pdf_btn': 'In PDF konvertieren',

    'ai.transcribe_title': 'Sprach- & Audio-Transkription',
    'ai.transcribe_subtitle': 'Laden Sie Audiodateien hoch oder nehmen Sie Ihre Stimme auf, um hochpräzisen Transkriptionstext zu erhalten.',
    'ai.record_start': 'Aufnahme starten',
    'ai.record_stop': 'Aufnahme stoppen',
    'ai.upload_audio': 'Audiodatei hochladen',
    'ai.transcribing': 'Transkription läuft...',
    'ai.copy_transcript': 'In Zwischenablage kopieren',
    'ai.download_txt': 'Textdatei herunterladen',

    // Editor Sidebar panels
    'editor.pages': 'Seiten',
    'editor.insert_blank': 'Leere Seite einfügen',
    'editor.compile_pdf': 'PDF kompilieren',
    'editor.add_text': 'Text hinzufügen',
    'editor.add_image': 'Bild hinzufügen',
    'editor.freehand': 'Freihand',
    'editor.comments': 'Kommentare',
    'editor.style': 'Stil',
    'editor.insert': 'Einfügen',
    'editor.ai': 'Assistent',
    'editor.track': 'Änderungen verfolgen',
    'editor.close': 'Schließen',
    'editor.close_panel': 'Panel schließen',
    'editor.saved_title': 'PDF gespeichert!',
    'editor.saved_desc': 'Ihr bearbeitetes Dokument wurde erfolgreich kompiliert.',

    // Auth & Workspace
    'auth.sign_in': 'Anmelden',
    'auth.sign_out': 'Abmelden',
    'auth.sign_in_google': 'Mit Google anmelden',
    'auth.account': 'Konto',
    'auth.verifying_status': 'Authentifizierungsstatus wird überprüft...',
    'auth.workspace_title': 'KI-Dokumenten-Workspace',
    'auth.workspace_desc': 'Melden Sie sich mit Ihrem Google-Konto an, um auf Ihren persönlichen KI-Dokumentenassistenten zuzugreifen, PDFs abzufragen und Ihren Arbeitsbereich zu behalten.',
    'auth.free_notice_title': '100% kostenlose Kernfunktionen:',
    'auth.free_notice_desc': 'Zusammenführen, teilen, komprimieren, konvertieren und bearbeiten bleiben völlig kostenlos und anonym ohne Anmeldung. Die Authentifizierung wird nur für den KI-Workspace benötigt.',
    'auth.dismiss': 'Schließen',
    'auth.signed_in_securely': 'Sicher mit Google angemeldet',
    'auth.connection_verified': 'Sichere Backend-Verbindung bestätigt',
    'auth.connection_failed': 'Sichere Verbindung konnte nicht bestätigt werden',
    'auth.verify_connection': 'Verbindung prüfen',
    'auth.verifying': 'Wird geprüft...',
    'auth.workspace_badge': 'KI-Workspace',
    'auth.workspace_subtitle': 'Interaktive Dokumentenanalyse basierend auf Google Gemini AI',
    'auth.session_info': 'Authentifizierte Sitzung',
    'auth.connection_status': 'Backend-Verbindungsstatus',
    'auth.active_notice_title': 'KI-Workspace aktiv',
    'auth.active_notice_desc': 'Ihre sichere Sitzung ist aktiv und bestätigt.',
    'auth.back_home': 'Zurück zur Startseite',
    'auth.user_avatar': 'Benutzer-Avatar',
    'auth.auth_gate_verified': 'Authentifiziert',
    'auth.no_email': 'Keine E-Mail verknüpft',
    'auth.error_popup_blocked': 'Das Anmelde-Popup wurde von Ihrem Browser blockiert. Bitte erlauben Sie Popups für diese Website und versuchen Sie es erneut.',
    'auth.error_cancelled': 'Die Anmeldung wurde abgebrochen. Bitte versuchen Sie es erneut.',
    'auth.error_network': 'Netzwerkfehler beim Verbinden mit den Authentifizierungsdiensten. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.',
    'auth.error_unauthorized_domain': 'Diese Anwendungsdomäne ist nicht für die Authentifizierung autorisiert. Bitte überprüfen Sie die Konfiguration der autorisierten Domänen.',
    'auth.error_user_disabled': 'Dieses Benutzerkonto wurde deaktiviert. Bitte kontaktieren Sie den Support.',
    'auth.error_generic': 'Anmeldung konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',

    // Workspace Management
    'workspace.title': 'Workspaces',
    'workspace.subtitle': 'Verwalten Sie Ihre privaten Dokumenten-Workspaces und benutzerdefinierten Systemanweisungen.',
    'workspace.create_new': 'Neuer Workspace',
    'workspace.create_title': 'Neuen Workspace erstellen',
    'workspace.name_label': 'Workspace-Name',
    'workspace.name_placeholder': 'z. B. Überprüfung juristischer Verträge',
    'workspace.instructions_label': 'Benutzerdefinierte Systemanweisungen',
    'workspace.instructions_placeholder': 'z. B. Sie sind ein sorgfältiger juristischer Analyst. Konzentrieren Sie sich auf Haftungsklauseln...',
    'workspace.instructions_help': 'Diese Anweisungen steuern die KI-Dokumentenanalyse für diesen Workspace (max. 4.000 Zeichen).',
    'workspace.create_btn': 'Workspace erstellen',
    'workspace.cancel': 'Abbrechen',
    'workspace.empty_title': 'Noch keine Workspaces',
    'workspace.empty_desc': 'Erstellen Sie Ihren ersten Workspace, um individuelle Anweisungen zu speichern und Dokumente zu verwalten.',
    'workspace.empty_action': 'Ersten Workspace anlegen',
    'workspace.rename': 'Umbenennen',
    'workspace.rename_title': 'Workspace umbenennen',
    'workspace.save': 'Speichern',
    'workspace.save_instructions': 'Anweisungen speichern',
    'workspace.saving': 'Speichern...',
    'workspace.saved': 'Anweisungen erfolgreich gespeichert',
    'workspace.delete': 'Löschen',
    'workspace.delete_confirm_title': 'Workspace löschen',
    'workspace.delete_confirm_desc': 'Möchten Sie diesen Workspace wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'workspace.confirm_delete': 'Ja, Workspace löschen',
    'workspace.error_load': 'Laden der Workspaces fehlgeschlagen.',
    'workspace.error_create': 'Erstellen des Workspace fehlgeschlagen.',
    'workspace.error_update': 'Aktualisieren des Workspace fehlgeschlagen.',
    'workspace.error_delete': 'Löschen des Workspace fehlgeschlagen.',
    'workspace.error_invalid_data': 'Ungültige Workspace-Daten angegeben.',
    'workspace.error_not_found': 'Workspace nicht gefunden.',
    'workspace.error_persistence_unavailable': 'Workspace-Speicher ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.',
    'workspace.error_unauthorized': 'Sie müssen angemeldet sein, um Workspaces zu verwalten.',
    'workspace.error_unknown': 'Ein unerwarteter Fehler ist aufgetreten.',
    'workspace.active': 'Aktiver Workspace',
    'workspace.select': 'Workspace auswählen',
    'workspace.chars_count': 'Zeichen',
    'workspace.created_at': 'Erstellt am',
    'workspace.updated_at': 'Aktualisiert am',
    'workspace.total_workspaces': 'Workspaces insgesamt',
    'workspace.instructions_empty': 'Bisher keine benutzerdefinierten Anweisungen hinterlegt.'
  },
  es: {
    // Nav & General
    'all_tools': 'Herramientas',
    'ai_tools': 'Herramientas de Medios',
    'compress': 'Comprimir',
    'convert': 'Convertir',
    'edit': 'Editar',
    'dark_mode_light': 'Cambiar a modo claro',
    'dark_mode_dark': 'Cambiar a modo oscuro',
    'toggle_menu': 'Alternar menú',
    'logo_title': 'MakePDFRight',
    'made_with': 'Hecho con ❤️ desde Kerala',
    'back_home': 'Volver al inicio',

    // Hero
    'hero_title_1': 'Haga bien sus ',
    'hero_title_2': 'PDF',
    'hero_title_3': '.',
    'hero_desc': 'Herramientas esenciales para organizar, convertir y optimizar documentos PDF en su navegador.',
    'ai_powered_tools_heading': 'Herramientas de Medios y Audio',
    'standard_pdf_tools_heading': 'Herramientas PDF Estándar',

    // Tools Names & Descriptions
    'tools.merge.name': 'Fusionar PDF',
    'tools.merge.description': 'Combine PDFs en el orden que desee con la herramienta para unir PDF más fácil disponible.',
    'tools.split.name': 'Dividir PDF',
    'tools.split.description': 'Extraiga una página o un conjunto completo para convertir fácilmente en archivos PDF independientes.',
    'tools.compress.name': 'Comprimir PDF',
    'tools.compress.description': 'Reduzca el tamaño del archivo optimizando al mismo tiempo para obtener la máxima calidad de PDF.',
    'tools.pdf_to_word.name': 'PDF a Word',
    'tools.pdf_to_word.description': 'Convierta fácilmente sus archivos PDF en documentos DOC y DOCX fáciles de editar.',
    'tools.pdf_to_excel.name': 'PDF a Excel',
    'tools.pdf_to_excel.description': 'Extraiga datos directamente de archivos PDF a hojas de cálculo de Excel en pocos segundos.',
    'tools.pdf_to_jpg.name': 'PDF a JPG',
    'tools.pdf_to_jpg.description': 'Extraiga todas las imágenes de un PDF o convierta cada página en una imagen JPG.',
    'tools.image_to_pdf.name': 'Imagen a PDF',
    'tools.image_to_pdf.description': 'Convierta imágenes JPG, PNG y otras a PDF en segundos.',
    'tools.edit.name': 'Editar PDF',
    'tools.edit.description': 'Añada texto, imágenes, formas o anotaciones a mano alzada a un documento PDF.',
    'tools.rotate.name': 'Rotar PDF',
    'tools.rotate.description': 'Rote sus PDF como los necesite. ¡Incluso puede rotar múltiples archivos PDF a la vez!',
    'tools.organise.name': 'Organizar PDF',
    'tools.organise.description': 'Ordene, agregue y elimine páginas PDF. Rote y reorganícelas según sus necesidades.',
    'tools.image_gen.name': 'Generador de imágenes',
    'tools.image_gen.description': 'Cree imágenes impresionantes a partir de descripciones de texto utilizando modelos avanzados.',
    'tools.generate_image.name': 'Generador de imágenes IA',
    'tools.generate_image.description': 'Cree imágenes a partir de descripciones de texto.',
    'tools.transcribe.name': 'Transcripción de Audio',
    'tools.transcribe.description': 'Convierta grabaciones de voz y archivos de audio en transcripciones de texto de alta precisión.',
    'tools.ocr.name': 'OCR PDF',
    'tools.ocr.description': 'Extraiga texto de documentos PDF escaneados con OCR.',

    // ToolPages Title & Details
    'tool.merge.title': 'Fusionar PDF',
    'tool.merge.desc': 'Combine múltiples archivos PDF en un solo documento en segundos.',
    'tool.split.title': 'Dividir PDF',
    'tool.split.desc': 'Extraiga páginas de su PDF o divídalo en múltiples archivos.',
    'tool.compress.title': 'Comprimir PDF',
    'tool.compress.desc': 'Reduzca el tamaño de su PDF manteniendo la calidad.',
    'tool.pdf_to_jpg.title': 'PDF a JPG',
    'tool.pdf_to_jpg.desc': 'Convierta páginas PDF en imágenes JPG de alta calidad.',
    'tool.image_to_pdf.title': 'Imagen a PDF',
    'tool.image_to_pdf.desc': 'Convierta imágenes JPG y PNG a PDF en segundos.',
    'tool.pdf_to_word.title': 'PDF a Word',
    'tool.pdf_to_word.desc': 'Convierta su PDF en un documento Word editable.',
    'tool.pdf_to_excel.title': 'PDF a Excel',
    'tool.pdf_to_excel.desc': 'Extraiga tablas y datos de PDF a hojas de cálculo de Excel.',
    'tool.edit.title': 'Editar PDF',
    'tool.edit.desc': 'Modifique texto y agregue imágenes a su documento PDF.',
    'tool.rotate.title': 'Rotar PDF',
    'tool.rotate.desc': 'Rote las páginas de su PDF y guárdelas permanentemente.',
    'tool.organise.title': 'Organizar PDF',
    'tool.organise.desc': 'Reordene, rote y elimine páginas de su PDF.',
    'tool.ocr.title': 'OCR PDF',
    'tool.ocr.desc': 'Reconozca y extraiga texto de archivos PDF escaneados.',
    'tool.generate_image.title': 'Generador de imágenes IA',
    'tool.generate_image.desc': 'Cree imágenes personalizadas a partir de indicaciones de texto.',
    'tool.transcribe.title': 'Transcripción de Audio',
    'tool.transcribe.desc': 'Convierta grabaciones de audio en texto preciso.',

    // File Upload
    'upload.choose': 'Elegir archivos PDF',
    'upload.or_drop': 'o arrastre los PDF aquí',
    'upload.select_button': 'Seleccionar archivos PDF',
    'upload.drop_active': 'Arrastre los archivos aquí...',

    // Core Interaction Buttons / States
    'common.processing': 'Procesando...',
    'common.loading': 'Cargando...',
    'common.success': '¡Éxito!',
    'common.error': 'Error',
    'common.download': 'Descargar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.add_files': 'Añadir más archivos',
    'common.clear_all': 'Borrar todo',

    // Specific Tool States
    'merge.merged_title': '¡Los PDF se han fusionado!',
    'merge.merged_desc': 'Su documento combinado está listo para descargar.',
    'merge.download_btn': 'Descargar PDF fusionado',
    'merge.more_btn': 'Fusionar más archivos',
    'merge.no_files': 'Aún no se han subido archivos. Añada algunos para empezar.',
    'merge.processing_msg': 'Fusionando sus archivos PDF en secuencia...',

    'split.split_title': '¡El PDF se ha dividido!',
    'split.split_desc': 'Sus páginas extraídas están listas para descargar.',
    'split.download_btn': 'Descargar páginas divididas',
    'split.more_btn': 'Dividir otro archivo',
    'split.processing_msg': 'Dividiendo su documento PDF...',
    'split.range_label': 'Rango de páginas (p. ej., 1-5, 8, 11-13)',
    'split.extract_btn': 'Extraer páginas',

    'compress.compressed_title': '¡El PDF se ha comprimido!',
    'compress.compressed_desc': 'Su documento optimizado está listo para descargar.',
    'compress.download_btn': 'Descargar PDF comprimido',
    'compress.more_btn': 'Comprimir otro archivo',
    'compress.processing_msg': 'Optimizando y comprimiendo su PDF...',
    'compress.level_label': 'Nivel de compresión',
    'compress.extreme_label': 'Compresión extrema (Calidad inferior)',
    'compress.recommended_label': 'Compresión recomendada (Buena calidad y tamaño)',
    'compress.less_label': 'Menor compresión (Alta calidad)',
    'compress.submit_btn': 'Comprimir PDF',

    'rotate.rotated_title': '¡El PDF se ha rotado!',
    'rotate.rotated_desc': 'Su documento modificado está listo para descargar.',
    'rotate.download_btn': 'Descargar PDF rotado',
    'rotate.more_btn': 'Rotar otro archivo',
    'rotate.processing_msg': 'Rotando páginas del PDF...',
    'rotate.clockwise': 'Rotar en sentido horario',
    'rotate.counter': 'Rotar en sentido antihorario',
    'rotate.save_btn': 'Guardar PDF rotado',

    'organise.saved_title': '¡El PDF se ha organizado!',
    'organise.saved_desc': 'Su documento organizado está listo para descargar.',
    'organise.download_btn': 'Descargar PDF organizado',
    'organise.more_btn': 'Organizar otro archivo',
    'organise.processing_msg': 'Guardando modificaciones...',
    'organise.drag_reorder': 'Arrastrar para reordenar',
    'organise.save_btn': 'Guardar cambios',

    // Convert Tools
    'convert.success_title': '¡Conversión completa!',
    'convert.success_desc': 'Su documento convertido está listo para descargar.',
    'convert.download_word': 'Descargar documento de Word',
    'convert.download_excel': 'Descargar hoja de cálculo de Excel',
    'convert.download_jpg': 'Descargar imágenes JPG',
    'convert.download_pdf': 'Descargar PDF convertido',
    'convert.more_btn': 'Convertir otro archivo',
    'convert.processing_word': 'Convirtiendo PDF a documento de Word...',
    'convert.processing_excel': 'Convirtiendo PDF a hoja de cálculo de Excel...',
    'convert.processing_jpg': 'Convirtiendo PDF a imágenes JPG...',
    'convert.processing_pdf': 'Convirtiendo imágenes a PDF...',
    'convert.convert_btn': 'Convertir documento',

    // AI Tools
    'ai.image_gen_title': 'Generador de imágenes',
    'ai.image_gen_subtitle': 'Cree impresionantes gráficos personalizados a partir de descripciones de texto simples.',
    'ai.prompt_placeholder': 'Describa lo que desea crear (p. ej., Una ciudad futurista al estilo cyberpunk, alta definición)...',
    'ai.style_label': 'Estilo visual',
    'ai.ratio_label': 'Relación de aspecto',
    'ai.generate_btn': 'Generar imagen',
    'ai.generating': 'Generando obra de arte...',
    'ai.download_visual': 'Descargar imagen',
    'ai.image_to_pdf_btn': 'Convertir a PDF',

    'ai.transcribe_title': 'Transcripción de voz y audio',
    'ai.transcribe_subtitle': 'Suba archivos de audio o grabe su voz para obtener transcripciones de texto altamente precisas.',
    'ai.record_start': 'Iniciar grabación',
    'ai.record_stop': 'Detener grabación',
    'ai.upload_audio': 'Subir archivo de audio',
    'ai.transcribing': 'Transcripción en progreso...',
    'ai.copy_transcript': 'Copiar al portapapeles',
    'ai.download_txt': 'Descargar archivo de texto',

    // Editor Sidebar panels
    'editor.pages': 'Páginas',
    'editor.insert_blank': 'Insertar página en blanco',
    'editor.compile_pdf': 'Compilar PDF',
    'editor.add_text': 'Añadir texto',
    'editor.add_image': 'Añadir imagen',
    'editor.freehand': 'Mano libre',
    'editor.comments': 'Comentarios',
    'editor.style': 'Estilo',
    'editor.insert': 'Insertar',
    'editor.ai': 'Asistente',
    'editor.track': 'Seguimiento de cambios',
    'editor.close': 'Cerrar',
    'editor.close_panel': 'Cerrar panel',
    'editor.saved_title': '¡PDF guardado!',
    'editor.saved_desc': 'Su documento editado se ha compilado con éxito.',

    // Auth & Workspace
    'auth.sign_in': 'Iniciar sesión',
    'auth.sign_out': 'Cerrar sesión',
    'auth.sign_in_google': 'Iniciar sesión con Google',
    'auth.account': 'Cuenta',
    'auth.verifying_status': 'Verificando estado de autenticación...',
    'auth.workspace_title': 'Espacio de Trabajo de Documentos IA',
    'auth.workspace_desc': 'Inicie sesión con su cuenta de Google para acceder a su asistente de documentos IA personal, consultar archivos PDF y conservar su espacio de trabajo.',
    'auth.free_notice_title': 'Herramientas básicas 100% gratuitas:',
    'auth.free_notice_desc': 'Fusionar, dividir, comprimir, convertir y editar siguen siendo completamente gratis y anónimos sin inicio de sesión. La autenticación solo es necesaria para el espacio de trabajo IA.',
    'auth.dismiss': 'Descartar',
    'auth.signed_in_securely': 'Sesión iniciada de forma segura con Google',
    'auth.connection_verified': 'Conexión segura de backend verificada',
    'auth.connection_failed': 'No se pudo verificar la conexión segura',
    'auth.verify_connection': 'Verificar conexión',
    'auth.verifying': 'Verificando...',
    'auth.workspace_badge': 'Espacio IA',
    'auth.workspace_subtitle': 'Análisis interactivo de documentos impulsado por Google Gemini AI',
    'auth.session_info': 'Sesión autenticada',
    'auth.connection_status': 'Estado de conexión backend',
    'auth.active_notice_title': 'Espacio IA activo',
    'auth.active_notice_desc': 'Su sesión segura está activa y verificada.',
    'auth.back_home': 'Volver al inicio',
    'auth.user_avatar': 'Avatar de usuario',
    'auth.auth_gate_verified': 'Autenticado',
    'auth.no_email': 'Sin correo electrónico adjunto',
    'auth.error_popup_blocked': 'El navegador bloqueó la ventana emergente de inicio de sesión. Permita las ventanas emergentes para este sitio e intente de nuevo.',
    'auth.error_cancelled': 'Se canceló el inicio de sesión. Por favor, inténtelo de nuevo.',
    'auth.error_network': 'Error de red al conectar con los servicios de autenticación. Verifique su conexión a internet e inténtelo de nuevo.',
    'auth.error_unauthorized_domain': 'Este dominio de aplicación no está autorizado para la autenticación. Verifique la configuración de dominios autorizados.',
    'auth.error_user_disabled': 'Esta cuenta de usuario ha sido inhabilitada. Comuníquese con el soporte.',
    'auth.error_generic': 'No se pudo completar el inicio de sesión. Por favor, inténtelo de nuevo.',

    // Workspace Management
    'workspace.title': 'Espacios de trabajo',
    'workspace.subtitle': 'Administre sus espacios de documentos privados e instrucciones del sistema personalizadas.',
    'workspace.create_new': 'Nuevo espacio',
    'workspace.create_title': 'Crear nuevo espacio',
    'workspace.name_label': 'Nombre del espacio',
    'workspace.name_placeholder': 'p. ej., Revisión de contratos legales',
    'workspace.instructions_label': 'Instrucciones del sistema personalizadas',
    'workspace.instructions_placeholder': 'p. ej., Eres un analista legal meticuloso. Enfócate en cláusulas de responsabilidad...',
    'workspace.instructions_help': 'Estas instrucciones guían el análisis de documentos por IA para este espacio (máx. 4,000 caracteres).',
    'workspace.create_btn': 'Crear espacio',
    'workspace.cancel': 'Cancelar',
    'workspace.empty_title': 'Aún no hay espacios',
    'workspace.empty_desc': 'Cree su primer espacio para guardar instrucciones personalizadas y administrar documentos.',
    'workspace.empty_action': 'Crear primer espacio',
    'workspace.rename': 'Renombrar',
    'workspace.rename_title': 'Renombrar espacio',
    'workspace.save': 'Guardar',
    'workspace.save_instructions': 'Guardar instrucciones',
    'workspace.saving': 'Guardando...',
    'workspace.saved': 'Instrucciones guardadas con éxito',
    'workspace.delete': 'Eliminar',
    'workspace.delete_confirm_title': 'Eliminar espacio',
    'workspace.delete_confirm_desc': '¿Está seguro de que desea eliminar este espacio de trabajo? Esta acción no se puede deshacer.',
    'workspace.confirm_delete': 'Sí, eliminar espacio',
    'workspace.error_load': 'Error al cargar los espacios de trabajo.',
    'workspace.error_create': 'Error al crear el espacio de trabajo.',
    'workspace.error_update': 'Error al actualizar el espacio de trabajo.',
    'workspace.error_delete': 'Error al eliminar el espacio de trabajo.',
    'workspace.error_invalid_data': 'Se proporcionaron datos de espacio de trabajo no válidos.',
    'workspace.error_not_found': 'Espacio de trabajo no encontrado.',
    'workspace.error_persistence_unavailable': 'El almacenamiento del espacio de trabajo no está disponible temporalmente. Inténtelo más tarde.',
    'workspace.error_unauthorized': 'Debe iniciar sesión para administrar los espacios de trabajo.',
    'workspace.error_unknown': 'Ocurrió un error inesperado.',
    'workspace.active': 'Espacio activo',
    'workspace.select': 'Seleccionar espacio',
    'workspace.chars_count': 'caracteres',
    'workspace.created_at': 'Creado el',
    'workspace.updated_at': 'Actualizado el',
    'workspace.total_workspaces': 'Total de espacios',
    'workspace.instructions_empty': 'Aún no se han configurado instrucciones personalizadas.'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language;
      if (saved && translations[saved]) {
        return saved;
      }
      // Detect browser language on first visit
      const browserLang = navigator.language.split('-')[0] as Language;
      if (browserLang && translations[browserLang]) {
        return browserLang;
      }
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const val = translations[language]?.[key] || translations['en']?.[key];
    if (val) return val;
    // Fallback: avoid leaking raw dot keys into the UI
    if (key.includes('.')) {
      const parts = key.split('.');
      const last = parts[parts.length - 1];
      return last.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
